services:
  api:
    image: 7d-backend:latest
    build:
      context: ./backend-api
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=my_app_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniosecretkey
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=my_app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d my_app_db"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network
    restart: unless-stopped

  compass:
    image: christba/7d-compass:latest
    ports:
      - "3005:80"
    networks:
      - app-network
    restart: unless-stopped

  graphhopper:
    image: graphhopper/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989"
    volumes:
      - ./graphhopper-vroom/data:/data
    environment:
      - JAVA_OPTS=-Xmx4g
    command: >
      -Dgraphhopper.datareader.file=/data/us-midwest-latest.osm.pbf
      -Dgraphhopper.graph.location=/data/graph-cache
      -Dgraphhopper.prepare.ch.weightings=no
      -Dgraphhopper.profile=car
    networks:
      - app-network
    restart: unless-stopped

  vroom:
    image: vroomvrp/vroom:latest
    container_name: vroom
    # NOTE: Port 3000 is already used by 'api'. Change if both need to run simultaneously.
    ports:
      - "3001:3000" # Changed host port to 3001 to avoid conflict
    volumes:
      - ./graphhopper-vroom/config/vroom_config.json:/vroom/config.json:ro
    command: vroom -c /vroom/config.json
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  kc_pgdata:
  minio-data: