cliArgs:
  geometry: false
  planmode: false
  threads: 4
  explore: 5
  limit: '1mb'
  logdir: '/..'
  logsize: '100M'
  maxlocations: 300
  maxvehicles: 200
  override: true
  path: ''
  port: 3000
  router: 'osrm'
  timeout: 300000
  baseurl: '/'
routingServers:
  osrm:
    car:
      host: 'osrm'
      port: '5000'
    bike:
      host: 'osrm'
      port: '5001'
    foot:
      host: 'osrm'
      port: '5002'

